---
title: "Hysteresis Index Calculator"
author: "Colin"
date: "7/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages(pacman)
#pacman::p_install(geometry)
pacman::p_load( tidyverse, lubridate, geometry )
```
#R Environment Dependencies: B1 (the finalized sheet) with an added column where storms have been identified.
                          #storms_info -- Like the added "Storm_ID" column in B1, storms_info can be generated using code that's in the "Storm_Identifier+Characterizer" file.



```{r calculate area of hysteresis loops using polyarea(). Save indices to a new column in storms_info}

storms_info$H_Index <- NA 
storms_info$polyarea <- NA

#get a unique list of storm starts. Ensure Na values are not included.
stormsstarts <- B1$Storm_ID[!is.na(B1$Storm_ID)] %>% unique()

#init counters
stormcount <- 0 


for( ID in stormsstarts){
 
  stormcount <- stormcount + 1
  
  stormdata <- filter( B1, Storm_ID == ID ) %>% filter( !is.na(SpCond_uScm) )
  
  storms_info[stormcount, "H_Index"] <- 
    polyarea(x=stormdata$Discharge, y=stormdata$SpCond_uScm) / (max(stormdata$Discharge) - min(stormdata$Discharge))

rm(stormsstarts, stormcount, ID, stormdata)
```