---
title: "StreamLab_QAQC"
author: "Mary Lofton & Lauren Wind"
date: "Oct. 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages
```{r}
#install.packages("pacman")
pacman::p_load(tidyverse, lubridate, zoo)
```

#read in Bridge 1 data and QAQC
```{r}
B1_WQ <- read_csv("./6_14_2019 Bridge_1 WQ.csv", skip = 1) %>%
  #get rid of rows with unit descriptions
  slice(-c(1:2)) %>%
  #make sure numbers are recognized as numbers, dates as dates, etc.
  mutate(DateTime = as.POSIXct(TIMESTAMP,format="%m/%d/%Y %H:%M",tz=Sys.timezone()),
         Record_number = as.double(RECORD),
         Temp_degC = as.double(Temp),
         SpCond_uScm = as.double(Con)*1000,
         pH = as.double(pH),
         Turb_NTU = as.double(Turb),
         DO_pct = as.double(DOpct),
         DO_mgL = as.double(DOmgl),
         Batt_V = as.double(Batt)) %>%
  mutate(Site = "Bridge_1") %>%
  #select only the columns we want
  select(Site, DateTime, Temp_degC, SpCond_uScm, pH, Turb_NTU, DO_pct, DO_mgL, Batt_V) 

B1_QA <- B1_WQ %>%
  mutate(Flag_Temp_degC = ifelse(Temp_degC < -5 | Temp_degC > 30, 1, 0),
         Flag_SpCond_uScm = ifelse(SpCond_uScm < 0, 1, 0),
         Flag_pH = ifelse(pH <0 | pH >14, 1, 0),
         Flag_Turb_NTU = ifelse(Turb_NTU < 0, 1, 0), 
         Flag_DO_pct = ifelse(DO_pct < 0 | DO_pct > 150, 1, 0),
         Flag_DO_mgL = ifelse(DO_mgL < 0 | DO_mgL > 18, 1, 0),
         Flag_Batt_V = ifelse(Batt_V < 11 | Batt_V > 13, 1, 0)) %>%
  filter(DateTime <= "2018-12-31 23:45:00" & DateTime >= "2012-12-31 23:45:00")

#dates when vars other than temp and DO came online? should probably populate w/ NAs

```

#Bridge 1 stage data and QAQC
```{r}
B1_stage <- read_csv("./6_14_2019 Bridge_1 Stage.csv", skip = 1) %>%
  #get rid of rows with unit descriptions
  slice(-c(1:2)) %>%
  #make sure numbers are recognized as numbers, dates as dates, etc.
  mutate(DateTime = as.POSIXct(TIMESTAMP,format="%m/%d/%Y %H:%M",tz=Sys.timezone()),
         Lvl_m = as.double(Lvl_m)) %>%
  mutate(Site = "Bridge_1") %>%
  #select only the columns we want
  select(Site, DateTime, Lvl_m) %>%
  filter(DateTime <= "2018-12-31 23:50:00" & DateTime >= "2012-12-31 23:50:00")

B1_stage_QA <- B1_stage %>%
  mutate(Discharge_cms = ifelse(Lvl_m < 0.7, 4.89292 * Lvl_m ^ 1.9887,13.599 * Lvl_m - 7.0945)) %>% #function to calculate discharge
  mutate(Flag_Lvl_m = ifelse(Lvl_m > 4, 1, 0),
         Flag_Discharge_cms = ifelse(Lvl_m > 4, 1, 0),
         Discharge_cms_perc = ifelse(Lvl_m >= quantile(Discharge_cms, probs = 0.90, na.rm = TRUE),1,0))

# check <- B1_stage_QA[rep(1:nrow(B1_stage_QA), each = 2), ]
# check[1:nrow(check) %% 2 == 0, ] <- NA
# 
# check1 <- check %>%
#   mutate(Stage_interp = na.approx(Lvl_m, maxgap = 12, rule = 2),
#          DateTime_interp = na.approx(as.POSIXct.numeric(DateTime, origin = "1960-01-01"), maxgap = 12, rule = 2))

hist(B1_stage_QA$Lvl_m, breaks = seq(0,2,by = 0.05))
abline(v=0.16,col="red")
abline(v=0.2,col="red")
abline(v=0.25,col="red")

# write.csv(B1_stage_QA, "c:/Users/Mary Lofton/Documents/RProjects/IGC_Stroubles/MakeEMLBridge1/stage_temp.csv",row.names = FALSE)


```

#Merge the two and flag pH, Turb, Cond according to Lvl
```{r}
B1_stage_merge <- B1_stage_QA 

B1_WQ_merge <- B1_QA 

#NOTE THAT THIS VERSION HAS A FLAG FOR DISCHARGE PERCENTILE WHICH SHOULD BE REMOVED IN THE DATA VERSION FOR EDI!!
B1 <- full_join(B1_WQ_merge, B1_stage_merge) %>%
  mutate(Stage_interp = na.approx(Lvl_m, maxgap = 4, rule = 2),
         Flag_SpCond_uScm = ifelse(!is.na(Stage_interp) & Stage_interp<0.25,ifelse(Flag_SpCond_uScm == 0,2,12), ifelse(Discharge_cms_perc == 1,3,Flag_SpCond_uScm)),
         Flag_pH = ifelse(!is.na(Stage_interp) & Stage_interp < 0.2, ifelse(Flag_pH == 0,2,12), Flag_pH),
         Flag_Turb_NTU = ifelse(!is.na(Stage_interp) & Stage_interp < 0.16 , ifelse(Flag_Turb_NTU == 0,2,12), Flag_Turb_NTU)) %>%
  select(-Lvl_m,-Discharge_cms,-Flag_Lvl_m,-Flag_Discharge_cms,-Stage_interp,-Discharge_cms_perc)
  
# write.csv(B1, "c:/Users/Mary Lofton/Documents/RProjects/IGC_Stroubles/MakeEMLBridge1/WQ_temp.csv",row.names = FALSE)



```



#Visualize how much data this QA is flagging
```{r}
B1_viz2 <- B1 %>%
  mutate(Month = month(DateTime),
         Year = year(DateTime),
         Flag_Temp_degC = as.factor(Flag_Temp_degC),
         Flag_SpCond_uScm = as.factor(Flag_SpCond_uScm),
         Flag_pH = as.factor(Flag_pH),
         Flag_Turb_NTU = as.factor(Flag_Turb_NTU),
         Flag_DO_pct = as.factor(Flag_DO_pct),
         Flag_DO_mgL = as.factor(Flag_DO_mgL),
         Flag_Batt_V = as.factor(Flag_Batt_V)) 

yrz <- unique(B1_viz2$Year)
months <- c(1:12)
var_cols <- c(3:9)
flag_cols <- c(10:16)
vars <- c("Temp_degC","SpCond_uScm","pH","Turb_NTU","DO_pct","DO_mgL","Batt_V")
flags <- c("Flag_Temp_degC","Flag_SpCond_uScm","Flag_pH","Flag_Turb_NTU","Flag_DO_pct","Flag_DO_mgL","Flag_Batt_V")

for (k in 1:length(var_cols)){

  datums <- B1_viz2[,c(2,var_cols[k],flag_cols[k],17,18)]
  
for (i in 1:length(yrz)){
  yr <- subset(datums, Year == yrz[i])
  
  for (j in 1:length(months)){
    month <- subset(yr, Month == months[j])
    p1 <- ggplot(data = month, aes_string(x = "DateTime", y = vars[k], colour = flags[k]))+
      geom_point()+
      theme_bw() +
      scale_color_manual(values = c("gray","red","blue","black"))+
      ggtitle(paste(vars[k],yrz[i],months[j],sep = "-"))
    ggsave(p1, filename = paste0("C:/Users/Mary Lofton/Documents/IGC/Stroubles_project/EDI_data_viz/",paste(vars[k],yrz[i],months[j],sep = "-"),".png"),height = 7, width = 14, units = "in")
  }
}
}
```


