---
title: "StreamLab_QAQC"
author: "Mary Lofton & Lauren Wind"
date: "April 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages
```{r}
#install.packages("pacman")
pacman::p_load(tidyverse, lubridate)
```

#read in Bridge 1 data and QAQC
```{r}
B1_WQ <- read_csv("./Bridge 1_WQ.csv", skip = 1) %>%
  #get rid of rows with unit descriptions
  slice(-c(1:2)) %>%
  #make sure numbers are recognized as numbers, dates as dates, etc.
  mutate(Date = as.POSIXct(TIMESTAMP,format="%m/%d/%Y %H:%M",tz=Sys.timezone()),
         Time = X2,
         meridiemoffset = ifelse(X3 == "AM",0,12),
         Record_number = as.double(RECORD),
         Temp_degC = as.double(Temp),
         SpCond_uScm = as.double(Con)*1000,
         pH = as.double(pH),
         Turb_NTU = as.double(Turb),
         DO_pct = as.double(DOpct),
         DO_mgL = as.double(DOmgl),
         Batt_V = as.double(Batt)) %>%
  #calculate datetime from date, time, AM/PM
  mutate(DateTime = Date + Time + meridiemoffset*3600) %>%
  #select only the columns we want
  select(DateTime, Record_number, Temp_degC, SpCond_uScm, pH, Turb_NTU, DO_pct, DO_mgL, Batt_V) %>%
  mutate(Bridge = 1)

B1_QA <- B1_WQ %>%
  mutate(Flag_Temp_degC = ifelse(Temp_degC < -5 | Temp_degC > 30, 1, 0),
         Flag_SpCond_uScm = ifelse(SpCond_uScm < 50 | SpCond_uScm > 1500, 1, 0),
         Flag_pH = ifelse(pH <6 | pH >9, 1, 0),
         Flag_Turb_NTU = ifelse(Turb_NTU < 0 | Turb_NTU > 1000, 1, 0), #Timpano et al. 2010
         Flag_DO_pct = ifelse(DO_pct < 0 | DO_pct > 150, 1, 0),
         Flag_DO_mgL = ifelse(DO_mgL < 4 | DO_mgL > 18, 1, 0),
         Flag_Batt_V = ifelse(Batt_V < 11 | Batt_V > 13, 1, 0))

#dates when vars other than temp and DO came online? should probably populate w/ NAs
```

#Bridge 2 read data and QAQC
```{r}

B2_WQ <- read_csv("./Bridge 2_WQ.csv", skip = 1) %>%
  #get rid of rows with unit descriptions
  slice(-c(1:2)) %>%
  #make sure numbers are recognized as numbers, dates as dates, etc.
  mutate(Date = as.POSIXct(TIMESTAMP,format="%m/%d/%Y %H:%M",tz=Sys.timezone()),
         Time = X2,
         meridiemoffset = ifelse(X3 == "AM",0,12),
         Record_number = as.double(RECORD),
         Temp_degC = as.double(Temp_degC),
         SpCond_uScm = as.double(`SpCond_mS/cm`)*1000,
         pH = as.double(pH),
         Turb_NTU = as.double(Turb_NTU),
         DO_pct = as.double(`DO_%`),
         DO_mgL = as.double(`DO_mg/l`),
         Batt_V = as.double(Batt_V_Min)) %>%
  #calculate datetime from date, time, AM/PM
  mutate(DateTime = Date + Time + meridiemoffset*3600) %>%
  #select only the columns we want
  select(DateTime, Record_number, Temp_degC, SpCond_uScm, pH, Turb_NTU, DO_pct, DO_mgL, Batt_V) %>%
  mutate(Bridge = 2)
```

#Bridge 1 stage data and QAQC
```{r}
B1_stage <- read_csv("./Bridge 1_Stage.csv", skip = 1) %>%
  #get rid of rows with unit descriptions
  slice(-c(1:2)) %>%
  #make sure numbers are recognized as numbers, dates as dates, etc.
  mutate(Date = as.POSIXct(TIMESTAMP,format="%m/%d/%Y %H:%M",tz=Sys.timezone()),
         Time = X2,
         meridiemoffset = ifelse(X3 == "AM",0,12),
         Record_number = as.double(RECORD),
         Lvl_m = as.double(Lvl_m)) %>%
  #calculate datetime from date, time, AM/PM
  mutate(DateTime = Date + Time + meridiemoffset*3600) %>%
  #select only the columns we want
  select(DateTime, Record_number, Lvl_m) %>%
  mutate(Bridge = 1)

B1_stage_QA <- B1_stage %>%
  mutate(Flag_Lvl_m = ifelse(Lvl_m < 0.2 | Lvl_m > 4, 1, 0))

```

#Bridge 2 stage data and QAQC
```{r}

B2_stage <- read_csv("./Bridge 2_Stage.csv", skip = 1) %>%
  #get rid of rows with unit descriptions
  slice(-c(1:2)) %>%
  #make sure numbers are recognized as numbers, dates as dates, etc.
  mutate(Date = as.POSIXct(TIMESTAMP,format="%m/%d/%Y %H:%M",tz=Sys.timezone()),
         Time = X2,
         meridiemoffset = ifelse(X3 == "AM",0,12),
         Record_number = as.double(RECORD),
         Lvl_m = as.double(Lvl_m)) %>%
  #calculate datetime from date, time, AM/PM
  mutate(DateTime = Date + Time + meridiemoffset*3600) %>%
  #select only the columns we want
  select(DateTime, Record_number, Lvl_m) %>%
  mutate(Bridge = 2)
```