---
title: "ggplot2 Experiments"
author: "Colin"
date: "7/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load( tidyverse, lubridate )
```


#read in finalized B1 sheet
```{r Data Read-In}

B1 <- read_csv("../Data_QAQC/Colin/B1.csv") %>%
  mutate( DateTime = parse_date_time( DateTime, "ymd H M S"),
        #As in "Storm_Identifier+Characterizer", create a new column where 1 demonstrates discharge being above the 99th percentile, 0 means it is not
        #Feel free to use other percentiles, of course.
        #It appears that we identify 609 unique storms if the 90th perentile is our threshold, and 122 storms if we use the 99th.
          Flag_High_Discharge = ifelse( Discharge > quantile( Discharge, 0.99, names = FALSE), 1, 0) )


BrynnDates <- read_csv( "./Visualize/Colin/Brynn_Dates.csv", col_names = FALSE )[[1]] %>%
  mdy()
  
```


```{r play around with graphing summaries for discharge }
#see the groupings for B1. These are set above

#Compute Maximum and Minimum Discharge
Month_MaxMin_Dis <- summarize( B1, MaxDischarge = max(Discharge), MinDischarge = min(Discharge), ) %>% 
  mutate( MonthName = month.name[Month] ) 


#reorder the columns so MonthNames isn't last
#A way to improve this would be to refer to the columns by name instead of original place
Month_MaxMin_Dis <- Month_MaxMin_Dis[ , c(1, 5, 2, 3, 4)]
Month_MaxMin_Dis


MaxDischarge.Plot <- ggplot( Month_MaxMin_Dis, aes( x = Year + Month/12, y = MaxDischarge, color = Month) ) + geom_point() + geom_path() + labs( title = "Maximum Discharge by Month") +
  annotate( "point", x = min(B1$Year + B1$Month/12 - .5), y = quantile(B1$Discharge, 0.9, names = FALSE), ) +
  annotate( "text", x = min(B1$Year + B1$Month/12 - .5), y = quantile(B1$Discharge, 0.9, names = FALSE), label = "99th Quantile")

last_plot()


MinDischarge.Plot <- ggplot( Month_MaxMin_Dis, aes( x = Year + Month/12, y = MinDischarge, color = Month) ) + geom_point() + geom_path() + labs( title = "Minimum Discharge by Month")

last_plot()


MaxMinDischarge.Plot <- ggplot( Month_MaxMin_Dis ) +
  geom_point(mapping = aes( x = Year + Month/12, y = MaxDischarge, color = Month)) +
  geom_path(mapping = aes( x = Year + Month/12, y = MaxDischarge, color = Month)) +
  geom_point(mapping = aes( x = Year + Month/12, y = MinDischarge, color = Month)) +
  geom_path(mapping = aes( x = Year + Month/12, y = MinDischarge, color = Month))
  

last_plot()

```



```{r graph every single discharge point}

#Look at patterns of discharge to identify storms and rainy seasons
ggplot(data = B1, aes(x = DateTime, y = Discharge, color = Flag_High_Discharge)) + geom_point() + geom_path()

last_plot()
```



```{r graph discharge by year}


years <- year(B1[[1,"DateTime"]]):year(B1[[nrow(B1),"DateTime"]])


for( vars in years ){

  print( ggplot( filter( B1,
                  year(DateTime) == vars ),
          aes(x = DateTime, y = Discharge, color = Flag_High_Discharge) ) +
    geom_point() + 
    geom_line() +
    labs( title = paste( vars, "Discharge") )
    )
}
```



```{r graph discharge by month within each year. Make LOTS of graphs...}
timestart_graphingbymonthyear <- Sys.time()


for( y_vars in years ){

  y_data <- filter( B1, year(DateTime) == y_vars )
  months <- month(y_data[[1,"DateTime"]]):month(y_data[[nrow(y_data),"DateTime"]])
  
  #visually check to be sure we have data from each month in the year
  print( paste( y_vars, month.name[months] ) )
  
  
  
  for( m_vars in months ){
      m_data <- filter( y_data, month(DateTime) == m_vars )
    
      ggplot( m_data,
              aes(x = DateTime, y = Discharge, color = Flag_High_Discharge) ) +
            geom_point() +
            geom_line() +
            coord_cartesian( ylim = c(0, 18),
                             #xlim = c( m_data$DateTime[1], m_data$DateTime[length(m_data)])
                             ) +
            labs( title = paste( y_vars, month.name[m_vars], "Discharge"), subtitle = "Storm Threshold set at 99th percentile of discharge, but check code if this seems out of date")
      
      ggsave( paste( "./Discharge Plots/", y_vars, " ", month.name[m_vars],  ".png", sep = "" ),
              width = 15, height = 8 )
    
  }
}

print( paste( "Graphing completed in:", Sys.time() - timestart_graphingbymonthyear, "minutes" ) )
rm( months, years y_vars, m_vars, y_data, m_data, timestart_graphingbymonthyear )

```


```{r graph turbidity for Izzy by month within each year}
timestart_graphingbymonthyear <- Sys.time()


for( y_vars in years ){

  y_data <- filter( B1, year(DateTime) == y_vars )
  months <- month(y_data[[1,"DateTime"]]):month(y_data[[nrow(y_data),"DateTime"]])
  
  #visually check to be sure we have data from each month in the year
  print( paste( y_vars, month.name[months] ) )
  
  
  for( m_vars in months ){
      m_data <- filter( y_data, month(DateTime) == m_vars )
    
      ggplot( m_data,
              aes(x = DateTime, y = Turb_NTU, color = Flag_Turb_NTU) ) +
            geom_point() +
            geom_line() +
            coord_cartesian( ylim = c(0, 2000 ) ) +
            labs( title = paste( y_vars, month.name[m_vars], "Turbidity") )
    
       ggsave( paste( "./Turbidity Plots/", y_vars, " ", month.name[m_vars],  ".png", sep = "" ),
              width = 13, height = 8 )
    
  }
}

print( paste( "Graphing completed in:", Sys.time() - timestart_graphingbymonthyear, "minutes" ) )
rm( months, years, y_vars, m_vars, y_data, m_data, timestart_graphingbymonthyear )

```