---
title: "Lag and Hysteresis Graphs"
author: "Colin Baciocco"
date: "7/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load( tidyverse, lubridate, grid, gridExtra )
```

#Environment Dependencies: B1 (the finalized sheet) with an added column where storms have been identified.
                          #storms_info -- Like the added "Storm_ID" column in B1, storms_info can be generated using code that's in the "Storm_Identifier+Characterizer" file.
                          #A column of pseudo-hysteresis indices in storms_info that's generated by Calc_Hyst_Indices.Rmd in the root directory 

```{r make and save figures with graphs of discharge + hysteresis for each storm, echo=FALSE}

#get a unique list of storm starts. Ensure Na is not included.
stormsstarts <- B1$Storm_ID[!is.na(B1$Storm_ID)] %>% unique()

#init counters
storm_count <- 0
storm_month <- 0

loopstart <- Sys.time()

#Loop through each storm, graphing and saving them one-by-one IF there's more than two rows of data.
for( ID in stormsstarts ){
  
  graphstart <- Sys.time()
  
  #pick out the data we're going to use 
  stormdata <- filter(B1, Storm_ID == ID)
  
  storm_count <- storm_count + 1
  
  #if the "storm" has more than two or three rows of data, graph and save it
  if( nrow(stormdata) > 6 ){
  
    #make graphs
    p_discharge <- ggplot( stormdata ) +
      #the function ensuring that the per-storm discharge graph has a common scale is commented out
      #coord_cartesian( ylim = c(0, max(B1$Discharge) ) ) +
      geom_path( mapping = aes( x = DateTime, y = Discharge ), color = "blue") +
      xlab("")
    
    p_spcond <- ggplot( stormdata ) +
      #Common scale for per-storm WQ graph is also commented out
      #coord_cartesian( ylim = c(0, max( B1$SpCond_uScm[!is.na(B1$SpCond_uScm)] ) ) ) +
      geom_path( mapping = aes( x = DateTime, y = SpCond_uScm), color = "brown" ) +
      xlab("")
    
    hyst <- ggplot( stormdata, aes(x = Discharge, y = SpCond_uScm, color = DateTime) ) +
      geom_path(arrow = arrow( angle = 40, ends = "last", length = unit(0.1, "inches"), type = "closed" ) )
    
    #only make a new graph for the discharge and conductivity over the entire month if it's a new month
    if( storm_month != month(ID) ){
      storm_month <- month(ID)
      d_month_graph <- ggplot( filter(B1, month(DateTime) == storm_month & year(DateTime) == year(ID)),
                             mapping = aes( x = DateTime, y = Discharge, color = Flag_High_Discharge )) +
        geom_path() +
        ggtitle(paste("Overall", month.name[storm_month],"Discharge"))
      
      #also make a monthly graph for whatever WQ measure is in the hysteresis plot
      q_month_graph <- ggplot( filter(B1, month(DateTime) == storm_month & year(DateTime) == year(ID)),
                             mapping = aes( x = DateTime, y = SpCond_uScm)) +
        geom_path(color = "brown") +
        ggtitle(paste("Overall", month.name[storm_month],"SpCond_uScm"))
      }
    
      
    #combine the graphs as one grob, or "graphics object", and add some descriptive text at the top
    p <- arrangeGrob( arrangeGrob( arrangeGrob( textGrob( paste( "Storm ID:", ID ) ),
                                     textGrob( paste( "Number of Storm Rows:", nrow(stormdata))),
                                     textGrob( paste( "Volume:", storms_info$Vol_mcubed[storm_count] %>%
                                                       round(3),  "m^3",
                                                      "    ",
                                                      "Time Span:", storms_info$length_H[storm_count] %>%
                                                       round(3), "Hours",
                                                      "    ", 
                                                      "*Intensity*:", storms_info$Intensity[storm_count] %>%
                                                       round(3), "m^3 / Hr")),
                                     textGrob( paste( "Number of NaN WQ values in Storm:",
                                                      sum(is.na(stormdata$SpCond_uScm))
                                                      )),
                                     textGrob( paste( "Hysteresis *Index*:", storms_info$H_Index[storm_count] %>%
                                                       round(3)))
                                     nrow = 5),
                                   d_month_graph,
                                   q_month_graph,
                                   nrow = 3),
                      arrangeGrob(p_discharge, p_spcond, nrow = 2),
                      hyst,
                      nrow = 3 )
    
    #save the grob as a picture
    png( paste( "./Storm Summaries/", ID, ".png", sep = "" ),
         width = 10, height = 12, units = "in", res = 200)
    grid.draw(p)
    dev.off()
    
    print( paste( "Graphing for", ID, "completed in", Sys.time() - graphstart, "seconds" ) )
  }
}


print( paste( "Graphing for all storms completed in", Sys.time() - loopstart, "minutes" ) )
rm(p_discharge, p_spcond, hyst, p, ID, stormsstarts, stormdata, loopstart, storm_count, graphstart, d_month_graph, q_month_graph, storm_month)
```
